[package]
name = "lazy-markdown"
description = "The laziest, most efficient markdown editor (citation needed)."
readme = "README.md"
edition = "2024"
version = "0.5.2"
license = "BlueOak-1.0.0"
repository = "https://github.com/Third-Thing/lazy-markdown"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/lazy-markdown", dest = "/usr/bin/lazy-markdown", mode = "755" },
    { source = "pkg/lazy-markdown.desktop", dest = "/usr/share/applications/lazy-markdown.desktop", mode = "644" },
    { source = "pkg/lazy-markdown-icon-256.png", dest = "/usr/share/icons/hicolor/256x256/apps/lazy-markdown.png", mode = "644" },
]

[dependencies]
atomic-write-file = { version = "0.3.0", features = ["unnamed-tmpfile"] }
gpui = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "1d217ee39d381ac101b7cf49d3d22451ac1093fe", features = [
    "font-kit",
    "wayland",
    "runtime_shaders",
] }

gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "063e55bbc4fb13907a988111e3581595cbcaefde", features = [
    "tree-sitter-markdown",
] }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "063e55bbc4fb13907a988111e3581595cbcaefde" }

# gpui-component = { path = "/my/src/gpui-component/crates/ui", features = [
#     "tree-sitter-languages",
# ] }
# gpui-component-assets = { path = "/my/src/gpui-component/crates/assets" }

image = { version = "0.25.10", default-features = false, features = ["png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
fontconfig-sys = { package = "yeslogic-fontconfig-sys", version = "6.0" }

[patch.crates-io]
psm = { git = "https://github.com/rust-lang/stacker", branch = "master" }
