[package]
name = "lazy-markdown"
description = "The laziest, most efficient markdown editor (citation needed)."
repository = "https://github.com/Third-Thing/lazy-markdown"
license = "BlueOak-1.0.0"
readme = "README.md"
edition = "2024"
version = "0.1.0"

[dependencies]
floem = { git = "https://github.com/Third-Thing/floem.git", rev = "16ff6bea81b77ac3b09ee02e45ab1857f0f9e731" }
